---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-grafana
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-prometheus
    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./tmc-cg/apps/grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-gitops
    namespace: tanzu-continuousdelivery-resources
 

