---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-prometheus
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-contour
    - name: tanzu-packages-package-repo
  interval: 1m0s
  path: ./tmc-cg/apps/prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-gitops
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus-server
      namespace: tanzu-system-monitoring


