#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
#@ if data.values.harbor.deploy:
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-extension-sa
  namespace: tanzu-system-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harbor-extension-role
  namespace: tanzu-system-registry
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harbor-extension-rolebinding
  namespace: tanzu-system-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harbor-extension-role
subjects:
- kind: ServiceAccount
  name: harbor-extension-sa
  namespace: tanzu-system-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-extension-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["clusterroles", "clusterrolebindings", "customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-extension-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-extension-cluster-role
subjects:
- kind: ServiceAccount
  name: harbor-extension-sa
  namespace: tanzu-system-registry
---
apiVersion: v1
data:
  values.yaml: #@ base64.encode(data.values.harbor.overlay)
kind: Secret
metadata:
  name: harbor-data-values
  namespace: tanzu-system-registry
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: harbor
  namespace: tanzu-system-registry
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  syncPeriod: 5m
  serviceAccountName: harbor-extension-sa
  fetch:
    - image:
        url: #@ data.values.tkgextensions.image
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - tkg-extensions/common
          - tkg-extensions/registry/harbor
        inline:
          pathsFrom:
            - secretRef:
                name: harbor-data-values
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]
#@ end