apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: openldap
spec: {}
status: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ldap
  namespace: openldap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ldap
  namespace: openldap
spec:
  commonName: openldap.openldap.svc.cluster.local
  dnsNames:
  - openldap
  - openldap.openldap.svc
  - openldap.openldap.svc.cluster.local
  ipAddresses:
  - 10.220.38.73
  issuerRef:
    kind: Issuer
    name: ldap
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: ldap
  usages:
  - server auth
  - key encipherment
  - digital signature
---
# Source: openldap/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "cGFzc3dvcmQ="
  LDAP_CONFIG_PASSWORD: "cGFzc3dvcmQ="
---
# Source: openldap/templates/configmap-customldif.yaml
#
# A ConfigMap spec for openldap slapd that map directly to files under
# /container/service/slapd/assets/config/bootstrap/ldif/custom
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-customldif
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
data:
  0-initial-ous.ldif: |-
    dn: ou=People,dc=pinniped,dc=dev
    objectClass: organizationalUnit
    ou: People

    dn: ou=Group,dc=pinniped,dc=dev
    objectClass: organizationalUnit
    ou: Group

    dn: cn=tanzu,ou=People,dc=pinniped,dc=dev
    objectclass: inetOrgPerson
    cn: tanzu
    sn: tanzu
    uid: tanzu
    userPassword: {SSHA}KmyLFAr0F0bydKMG3H7RsUNZTzAtq6hJ

    dn: cn=tanzu-users,ou=Group,dc=pinniped,dc=dev
    objectclass: groupOfUniqueNames
    cn: tanzu-users
    sn: tanzu-users
    uniqueMember: cn=tanzu,ou=People,dc=pinniped,dc=dev

---
# Source: openldap/templates/configmap-env.yaml
#
# A ConfigMap spec for openldap slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://github.com/osixia/docker-openldap#beginner-guide
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-env
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
data:
  LDAP_BACKEND: hdb
  LDAP_DOMAIN: pinniped.dev
  LDAP_ORGANISATION: VMware Tanzu POC
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_MASSWORD: password
  LDAP_READONLY_USER_USERNAME: readonly
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_TLS: "true"
  LDAP_TLS_CA_CRT_FILENAME: ca.crt
  LDAP_TLS_CRT_FILENAME: tls.crt
  LDAP_TLS_KEY_FILENAME: tls.key
  BITNAMI_DEBUG: "true"
  LDAP_ADMIN_USERNAME: admin
  LDAP_ROOT: "dc=pinniped,dc=dev"
  LDAP_USER_DC: "dc=pinniped,dc=dev"
  LDAP_USERS: "pinny,wally"
  LDAP_PASSWORDS: "pinny123,wally123"
  LDAP_GROUP: "users"
  LDAP_ENABLE_TLS: "yes"
  LDAP_TLS_VERIFY_CLIENT: "try"
---
# Source: openldap/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: openldap/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
spec:
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: ldap-port
    - name: ssl-ldap-port
      protocol: TCP
      port: 636
      targetPort: ssl-ldap-port
  selector:
    app: openldap
    release: openldap
  type: LoadBalancer
---
# Source: openldap/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
      release: openldap
  template:
    metadata:
      annotations:
        checksum/configmap-env: b502f31965efa9ea311c824f4b24d0aeec8de07153c6ae790375455eafeada80
        checksum/configmap-customldif: 456fe383c8b6c9aeccc479f7bd02eb5685596f3ccfada03de8c8384d8036216f
      labels:
        app: openldap
        release: openldap
    spec:
      initContainers:
      - name: openldap-init-ldif
        image: harbor.mgt.mytanzu.org/tools/busybox:latest
        command: ['sh', '-c', 'cp /customldif/* /ldifworkingdir']
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: customldif
          mountPath: /customldif
        - name: ldifworkingdir
          mountPath: /ldifworkingdir
        resources:
          {}
      containers:
        - name: openldap
          image: "harbor.mgt.mytanzu.org/tools/openldap:1.2.4"
          imagePullPolicy: IfNotPresent
          args:
            - -l
            - debug
            - --copy-service
          ports:
            - name: ldap-port
              containerPort: 389
            - name: ssl-ldap-port
              containerPort: 636
          envFrom:
            - configMapRef:
                name: openldap-env
            - secretRef:
                name: openldap
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: data
            - name: data
              mountPath: /etc/ldap/slapd.d
              subPath: config-data
            - name: ldifworkingdir
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
            - mountPath: /container/service/slapd/assets/certs
              name: certs
          livenessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {}
      volumes:
        - name: customldif
          configMap:
            name: openldap-customldif
        - name: ldifworkingdir
          emptyDir: {}
        - name: certs
          secret:
            secretName: ldap
        - name: data
          persistentVolumeClaim:
            claimName: openldap
---
#apiVersion: idp.supervisor.pinniped.dev/v1alpha1
#kind: LDAPIdentityProvider
#metadata:
#  name: openldap
#spec:
#  bind:
#    secretName: openldap-bind-account
#  groupSearch:
#    attributes:
#      groupName: cn
#    base: dc=pinniped,dc=dev
#    filter: (objectClass=groupOfNames)
#  host: "openldap.openldap.svc.cluster.local"
#  tls:
#    certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZkVENDQTEyZ0F3SUJBZ0lSQU1oUlhLMGlFVkxMMFpNUmhLcDRvd2t3RFFZSktvWklodmNOQVFFTEJRQXcKTGpFc01Db0dBMVVFQXhNamIzQmxibXhrWVhBdWIzQmxibXhrWVhBdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3dwpIaGNOTWpNd016RXlNVEV6TURRMldoY05Nak13TmpFd01URXpNRFEyV2pBdU1Td3dLZ1lEVlFRREV5TnZjR1Z1CmJHUmhjQzV2Y0dWdWJHUmhjQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiRENDQWlJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnSVBBRENDQWdvQ2dnSUJBTWhwd0pUWUZOb2RMUnVNbzNVczduNXJTZFRYQUVXQVNiUG1wVjN2bTVPTQpwcFl0YWh4T2FMc0ovZEI2d0FkdElwRG1taWw3cVpUTytVd1hta2Vuc0d6MEMyTllHUGJLek8rR1lHSTlSVXVOCkkxWEtYVU9pZHh1dWJzN1ZrbUU5RzNkNkVIVHN2b0xUZTZWdGw5WVFUbjRnczZlclZYWGpnaDZXNkQxb0EwakMKRHVCTW5SejlKVVFhMWw4RmZIaFEwSno4QzhUL1Nwc2ZBZkhSajdld3JIbWV3QmE3ZXNBTkJKaDZNQ3dxM09aRgozanNJdDZSQ1YyVHNKeVB3ZHJLSDV3ZFdUTkZyeUlaUkYwc2xZMm5RT1BJaHRZU0l0b1VwVXFxRzYwTGZnOWt6CmovZFZRUGdnVHFwWmxkVFowTDNoRzZodXdZbFZ2SjlqWjlsbmZDMkVTSDE0QkJucmFRcDRVN2t1L2E0YzlDR1cKWHF0M09EampvcG1SRit5ZGJHQjYrQ2hJTDZzMWtoaWNnbFdaQnpJQXdvMG9uc0t0YUIycjRBWjNJckxMZ29BQgpoVnRZdnVXT0VCNE5NOEk1V0ZsWkpxYms1NVZsMHA5UHR4emxoajVuSkpVb2FOV21SSFVaZjBwU2dORVVCZjV2CnkwWG5CYkZtTXhhQVNvWVVVY3ZIUjhlN0xlWVFLNGlzZm1tRkZob3BxcEFDclpwY2xRTU9IZlhlTDNhWWJ1bGEKalpzRnFzMnBYc1lTN0tvaE9STEl5aFBVa00xV1hTejcxSmh0T1BoaTk5RStoUEhKd0N1c3NHcjNIR01xamluQgo0d2JvZVVSK0ZzdWI4MHppenFlMjdMQVJzb01NRGhsWUJxcEpqQ3QvdERyTitjMXVxendLYnBnOWZJSGFJaGZICkFnTUJBQUdqZ1kwd2dZb3dEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTU1Bb0dDQ3NHQVFVRkJ3TUIKTUF3R0ExVWRFd0VCL3dRQ01BQXdWUVlEVlIwUkJFNHdUSUlJYjNCbGJteGtZWENDRlc5d1pXNXNaR0Z3TG05dwpaVzVzWkdGd0xuTjJZNElqYjNCbGJteGtZWEF1YjNCbGJteGtZWEF1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3lICkJBcmNKa2t3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUFyUFVyL21IVFQydjl2Nm9yanZXMWxGSjUrTkZFS3EKTTZncHNjRkFiWDdHZEtnbGl4NldTQ1J4QVd2N1lkU0xQRUxhMkVjTng1UW5ReWdqWC9NNW96V1g5cFhQV0tHKwpnWDdMdkJPZGxQQjA3Rk9uTmRMWUhscXorckc2UFgwdmVYQkE0eFU2WGg0WnUxSTJlRG1mTHhlNW1VaU1uMnhvCmpKNm8xd1BFaVg4SmJtMFBMY29UVDY5Vi9OV2QxajEyTHMyNXB1YUJmNDFvZE9LVlo0bHN5VFI4Skg5Q1dDeWwKNTNxeUN4RTRGdDZjbFZsdUlpcHVNY1ArNnh4c1lrYVJKUEJWVy9LTDQwa040eDJ3NWhmMDlHcXQwNXdFREc0bQpiVG1vN0Z2ak96UjZwdkZoNEt2N0hUQ1EwOUUrZDlOeXc4VlowZXBTeDByYlJQMjhNM1hsRkJQRVQ0U0gyNHhlClM5MlFrV0pkTnRaRGZlZWYyajV0OFZJWVI2a05LeWhIMDRMQjRjK3kxQXN3bzBRbWN0S0hOakp4U0pwK3hVaDUKSUVoVVlzc3hSejU4UTF1SXNGa3JVLzd1Q2JLNlU0UEFFV3JwbzlhQnFTRWt5Ym5JWDNxcmU3Q2pIMEVubnBEbApVd1hCRjc4VFlQaDV4NXpvY1grQUJFMjVFbkdMb2dWSTNKc3k0bHd6djk3anFQZzhoTDJUa0VxWVJ0dy9aS3hRCmovWmtrY0daQ2xKMis5VkdHa2FTL3BOWnFZdjJnVkV6S0lUT1lkcWxGczZpTjRDMk95SWRwT2ZUSzB4VlFzbFoKNzhDYWg5UlhPaDJ6b0FOQVFxR1J6Y1ROaXZPVUYvV0s5MGtoMzFSOUozTjRZSHpzVzVsTjhyek5nVmsxc0JrOApUWjJEVU5OWVM3NkoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#  userSearch:
#    attributes:
#      uid: cn
#      username: cn
#    base: dc=pinniped,dc=dev
#    filter: (objectClass=inetOrgPerson)
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: openldap-bind-account
#type: kubernetes.io/basic-auth
#stringData:
#  username: "cn=admin,dc=pinniped,dc=dev"
#  password: "password"
