---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-package-repo
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-namespaces
  interval: 1m0s
  path: ./tmc-cg/02-service-accounts/package-repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-gitops
    namespace: tanzu-continuousdelivery-resources


