---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-namespaces
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./tmc-cg/apps/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: tanzu-gitops
    namespace: tanzu-continuousdelivery-resources


