---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-efk-sa
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-namespaces
  interval: 1m0s
  path: ./tmc-cg/02-service-accounts/efk-sa
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-poc
 

