---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-ibm-mq
  namespace: mq
  labels:
    app: "ibm-mq"
    chart: "ibm-mqadvanced-server-dev"
    heritage: "Helm"
    release: "RELEASE-NAME"
imagePullSecrets:
  - name: sa-mq
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9157'
  name: release-name-ibm-mq-metrics
  namespace: mq
  labels:
    app: "ibm-mq"
    chart: "ibm-mqadvanced-server-dev"
    heritage: "Helm"
    release: "RELEASE-NAME"
spec:
  type: ClusterIP
  ports:
  - targetPort: 9157
    port: 9157
    protocol: TCP
  selector:
    app: "ibm-mq"
    release: "RELEASE-NAME"
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-ibm-mq
  namespace: mq
  labels:
    app: "ibm-mq"
    chart: "ibm-mqadvanced-server-dev"
    heritage: "Helm"
    release: "RELEASE-NAME"
spec:
  type: LoadBalancer
  ports:
  - port: 9443
    name: console-https
  - port: 1414
    name: qmgr
  selector:
    app: "ibm-mq"
    release: "RELEASE-NAME"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-ibm-mq
  namespace: mq
  labels:
    app: "ibm-mq"
    chart: "ibm-mqadvanced-server-dev"
    heritage: "Helm"
    release: "RELEASE-NAME"
spec:
  selector:
    matchLabels:
      app: "ibm-mq"
      chart: "ibm-mqadvanced-server-dev"
      heritage: "Helm"
      release: "RELEASE-NAME"
  serviceName: qm
  replicas: 1
  template:
    metadata:
      annotations:
        productID: "2f886a3eefbe4ccb89b2adb97c78b9cb"
        productName: "IBM MQ Advanced for Developers"
        productVersion: "9.1.5.0"
        productMetric: "FREE_USAGE"
        productChargedContainers: ""
      labels:
        statefulSetName: "release-name-ibm-mq"
        app: "ibm-mq"
        chart: "ibm-mqadvanced-server-dev"
        heritage: "Helm"
        release: "RELEASE-NAME"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "amd64"
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - "linux"
      serviceAccountName: release-name-ibm-mq
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      containers:
        - name: qmgr
          image: "ibmcom/mq:9.2.2.0-r1"
          imagePullPolicy: IfNotPresent
          terminationMessagePath: "/run/termination-log"
          ports:
          - containerPort: 1414
          - containerPort: 9443
          - containerPort: 9157
          env:
          - name: LICENSE
            value: accept
          - name: MQ_QMGR_NAME
            value: myqueuemanager
          - name: MQ_MULTI_INSTANCE
            value: "false"
          - name: LOG_FORMAT
            value: basic
          - name: MQ_ENABLE_METRICS
            value: "true"
          - name: DEBUG
            value: "false"
          - name: MQ_ENABLE_TRACE_STRMQM
            value: "false"
          - name: MQ_EPHEMERAL_PREFIX
            value: "/run/mqm"
          - name: MQ_GRACE_PERIOD
            value: "29"
          - name: MQ_ADMIN_PASSWORD
            value: "VMware1!"
          volumeMounts:
          - mountPath: "/mnt/mqm"
            name: data
          securityContext:
            readOnlyRootFilesystem: false
            privileged: true
          livenessProbe:
            exec:
              command:
              - chkmqhealthy
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            exec:
              command:
              - chkmqready
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 1
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: "ibm-mq"
        chart: "ibm-mqadvanced-server-dev"
        heritage: "Helm"
        release: "RELEASE-NAME"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "2Gi"
