---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: cert-manager-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-packages-sa
  namespace: packages
---
apiVersion: v1
kind: Secret
metadata:
  name: overlay-secret-cert-manager
  namespace: packages
stringData:
  patch.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Namespace", "metadata":{"name":"cert-manager"}})
    #@overlay/match-child-defaults missing_ok=True
    ---
    metadata:
      #@overlay/match missing_ok=True
      labels:
        #@overlay/merge
        pod-security.kubernetes.io/enforce: "privileged"
---
apiVersion: v1
kind: Secret
metadata:
  name: overlay-override-cert-manager
  namespace: packages
stringData:
  patch-cert-manager.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"PackageInstall", "metadata": {"name": "cert-manager"}})
    ---
    metadata:
      annotations:
        #@overlay/match missing_ok=True
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: overlay-secret-cert-manager
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-manager-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-manager-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-manager-packages-sa
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: overlay-override-cert-manager
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: cert-manager
  namespace: packages
spec:
  serviceAccountName: cert-manager-packages-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.7.2+vmware.3-tkg.3