#@ load("@ytt:data", "data")
---
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: LDAPIdentityProvider
metadata:
  name: openldap
  namespace: tmc-local
spec:
  bind:
    secretName: openldap-bind-account
  groupSearch:
    attributes:
      groupName: cn
    base: dc=pinniped,dc=dev
    filter: (objectClass=groupOfUniqueNames)
  host: "openldap.openldap.svc.cluster.local"
  tls:
    certificateAuthorityData: #@ data.values.ldapCa
  userSearch:
    attributes:
      uid: cn
      username: cn
    base: dc=pinniped,dc=dev
    filter: (objectClass=inetOrgPerson)
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-bind-account
  namespace: tmc-local
type: kubernetes.io/basic-auth
stringData:
  username: "cn=admin,dc=pinniped,dc=dev"
  password: "password"