apiVersion: v1
kind: Secret
metadata:
  name: prometheus-overlay-secret
  namespace: tmc-local
stringData:
  patch.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"StatefulSet", "metadata": {"name": "prometheus-server-tmc-local-monitoring-tmc-local"}})
    ---
    spec:
      volumeClaimTemplates:
        #@overlay/match by=overlay.all,expects="0+"
        #@overlay/match-child-defaults missing_ok=True
        - spec:
            resources:
              requests:
                storage: 25Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: tmc-overlay-override-prom-pvc
  namespace: tmc-local
stringData:
  patch-oidc.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"PackageInstall", "metadata": {"name": "tmc-local-monitoring"}})
    ---
    metadata:
      annotations:
        #@overlay/match missing_ok=True
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: prometheus-overlay-secret