apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: dns-server
spec: {}
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
  namespace: dns-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dns-server
  name: dns-server
  namespace: dns-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dns-server
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dns-server
    spec:
      containers:
        - env:
            - name: DNS_SERVER_DOMAIN
              value: dns-server
          image: projects.registry.vmware.com/tanzu_meta_pocs/tools/dns-server:latest
          name: dns-server
          ports:
            - containerPort: 5380
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
          resources: {}
          volumeMounts:
            - mountPath: /etc/dns
              name: config
      hostname: dns-server
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dns-server
  name: dns-server
  namespace: dns-server
spec:
  type: LoadBalancer
  ports:
    - name: "5380"
      port: 5380
      targetPort: 5380
    - name: "53"
      port: 53
      protocol: UDP
      targetPort: 53
    - name: 53-tcp
      port: 53
      targetPort: 53
  selector:
    io.kompose.service: dns-server