apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cc-06
  namespace: dev
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.20.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/16
  topology:
    class: tanzukubernetescluster
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=photon,os-version=3,os-arch=amd64
      replicas: 1
    variables:
    - name: controlPlaneVolumes
      value:
      - capacity:
          storage: 50G
        mountPath: /var/lib/etcd
        name: etcd
        storageClass: tanzu
    - name: nodePoolVolumes
      value:
      - capacity:
          storage: 100G
        mountPath: /var/lib/containerd
        name: containerd
        storageClass: tanzu
    - name: vmClass
      value: best-effort-large
    - name: storageClass
      value: tanzu
    - name: ntp
      value: time1.oc.vmware.com
    - name: trust
      value:
        additionalTrustedCAs:
          - name: CompanyInternalCA-1
            data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdIVENDQkFXZ0F3SUJBZ0lVYW53SzZRMUxLME1tNjNydFQ5cGtPdXhYYThNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daMHhDekFKQmdOVkJBWVRBbFJTTVJFd0R3WURWUVFJREFoSmMzUmhibUoxYkRFUk1BOEdBMVVFQnd3SQpTWE4wWVc1aWRXd3hEekFOQmdOVkJBb01CbFpOZDJGeVpURU9NQXdHQTFVRUN3d0ZWR0Z1ZW5VeEtEQW1CZ05WCkJBTU1IeW91ZEcxakxtZ3lieTAwTFRjMU9Ua3VhREp2TG5adGQyRnlaUzVqYjIweEhUQWJCZ2txaGtpRzl3MEIKQ1FFV0RtRnpaRUIyYlhkaGNtVXVZMjl0TUI0WERUSXpNRE13TVRFME1ETXpNMW9YRFRJMU1USXhPVEUwTURNegpNMW93Z1oweEN6QUpCZ05WQkFZVEFsUlNNUkV3RHdZRFZRUUlEQWhKYzNSaGJtSjFiREVSTUE4R0ExVUVCd3dJClNYTjBZVzVpZFd3eER6QU5CZ05WQkFvTUJsWk5kMkZ5WlRFT01Bd0dBMVVFQ3d3RlZHRnVlblV4S0RBbUJnTlYKQkFNTUh5b3VkRzFqTG1neWJ5MDBMVGMxT1RrdWFESnZMblp0ZDJGeVpTNWpiMjB4SFRBYkJna3Foa2lHOXcwQgpDUUVXRG1GelpFQjJiWGRoY21VdVkyOXRNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDCkFnRUFvdlBEb09XK01qak5kaEFGU0pnams1WVZKT3dnMk05SmdyVHd4T2xMUDBLM1J5a29PZVRUZWFUYmJxc2UKY1EzdXd4OHBEUHNaakJOL2JTdElXdEMvZkNtY0VpTmlKMmhEUDdVUkY4T0FMMlJ6NTlQdGd6WnphVjBvM3BiZApzcHRHM2FFRnpWYitIYXNIcWhKTkg0Q01KaTdpUlJiMHlld3ArbUVCTUQvYmFEUFVKNVo2M3YvVlhaWU92KzJVCmpibEJYUm44RUJQMnFBM1oyOWo4YTJkOWF2TWxvVlhSOW5saVBKTmpQcS8zN3hiSlpLK0wrbnRvemdSMGkwRksKTEc2UFUyQnFrWGJ5MXNSYUpUZ2NLQldmelZxN1MwcnBjSUtQOGxqZWl4WTgyaXFoOW53L1IyNTAzS2RjUUtrbgora2hEdkd3VmhyY1d2eXRiUzhkMkZGOFNUb3RGUk5UMG1xV3UrOFR6dXcvZUFLK2hTVFAzVXVIWVc4ekRHalVRClBDakV2cTArb3pVZ2JuazJFaVdDUHRISzJReUZkSjNSUkJGUGZXK2YzelplQmlPR3JOTmdLVzJJOVpwM3R6Q0cKc3ZzaUZ6aEJNRFhXOGRVK0lZSm9sZGNhdFZlUCtPVXdVYVE1clVFaU0vWTkzSWJPaHVzVHNQQUhpL2syaVlqQwppTHNMM2l1aTFSY3oxT0lOZ1p2VmtnOVdxaHFxMW9CZlpDKytNby9DQ0xNcXpQNmptMXZDdmhJZVMzWlI5ZUNECm5QS1A1TFFTYlpUc2N4eHkwWXFXY2tuYmRxWTZyay9wTzg1Rk8zVEdtZEZVSndzazRzYkpGTUVwRWRyK25lRjkKNjk5eURzKzkwOEhIVVZFWG1Celg5YSs1Vmh1ZGsyYU45cnVKWnpZZDlUT3ZqcnNDQXdFQUFhTlRNRkV3SFFZRApWUjBPQkJZRUZOYWVDRmhaK3lGV29XNjJmbW9ZMzAvendpVlRNQjhHQTFVZEl3UVlNQmFBRk5hZUNGaForeUZXCm9XNjJmbW9ZMzAvendpVlRNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUIKQUJkUDdwNlF2dnBpekU3VmIxK0IrMVFCTFVUMUM2WWkyV0JhUkRtKzZXUC84a0JySGo1WEZISEhXOHdiQ0hidwpyemFTOXZUVVVvN2Z1bjlIYmJFMGxHTFk3ZmZWZ3JKVjZkdDlseTVTRlB2N2VyamNBaEQwWW8wODIzd3Y2alNnCndxU2ZHZlVpR3NMWUpnMjYwR2xrVTVnWmF6Qm16ZTlPU3R4WFdhcjUwdmxjU1c3bXN5ajRXa2xBMTBuRDY5aXgKeE1OalFZM2VrK0RRVll4Z3VjZTd5VWFaNjRLanB3eVU4dExQQVNhZFdpRmxId0w0M0lSSGpaVXNaajI2Nm1EMgpGMnFyZmk2UzNYeWNzL2NFUTRkdTRVQk1HY2RCQ0JkYnRpbzd4ZVFmb0RLQzhpbGs1cS93elNaZGtpSXg0YzEyClRoT2w0bHdPV0o0c3ZqVXE5ZW4rN2p2UXdLRDI0Tk4vYzk3QWNHTnJBWUFuVTZOYVdSQmg4U2kvV2NHQ3R6RUMKeGd3VmZMV0ZIRW5VekE0STEwM0U0YmRGL1Vja1NUUndtdmkxNFBkbktiRHdvQm1vWHZTcUlJcXI2cHc4NzdlZgpwVUczcHJ1SkVTdmc0K1NQL3dPeDBpUld0SHRVU0RMWnJqamFaZFJwM1poSU5HYWIvWlpvS2xtYVArOEtNRHFXCkRxVkdnUEFYc0M3VkFwc0xVTUhaaWxieWgvL1I5a2dHdGZzZUtLYkN0L2R5OW5BNHg0akxUSFZWcUpYamdBZnoKazFqbFNPSmZxQy9zYnFuM05mdU9TZDFWaWVHNmw4cFdwWUVFRTN2TGhDY0tQdTg5WjhXWFczVGJ6THRSRHRvNQpKL3FFYVBoQjBCaVFIZjF5RzFpZHlaak1ZeFV6VVNScW4xdVlEMlpPSHVxawotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    version: v1.23.8+vmware.2
    workers:
      machineDeployments:
      - class: node-pool
        metadata:
          annotations:
            run.tanzu.vmware.com/resolve-os-image: os-name=photon,os-version=3,os-arch=amd64
        name: md-0
        replicas: 2
        variables:
          overrides:
          - name: vmClass
            value: best-effort-2xlarge
          - name: storageClass
            value: tanzu
