#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  username: #@ base64.encode(data.values.app.user)
  password: #@ base64.encode(data.values.app.passw)
kind: Secret
metadata:
  name: gorkem-secret
  namespace: #@ "{}".format(data.values.namespace)
type: Opaque