apiVersion: v1
stringData:
  values.yaml: |
    ---
    namespace:
      admin: ["admin","gorkem"]
      dev: ["john", "jane"]
    ingress:
      fqdn: tmc.h2o-4-12022.h2o.vmware.com
      class_name: "tmc-local"
    harbor:
      fqdn: harbor.tmc.h2o-4-12022.h2o.vmware.com
kind: Secret
metadata:
  creationTimestamp: null
  name: octant-values
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octant-deploy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: package-install-admin-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: octant-deploy-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: package-install-admin-role
subjects:
- kind: ServiceAccount
  name: octant-deploy-sa
  namespace: default
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: octant-app
  namespace: default
spec:
  serviceAccountName: octant-deploy-sa
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --kube-api-qps=20
      - --kube-api-burst=30
  fetch:
  - git:
      url: https://git.tmc.h2o-4-12022.h2o.vmware.com/tanzu/tanzu-gitops
      ref: origin/main
      subPath: apps/octant/gitops
  template:
  - ytt:
      ignoreUnknownComments: true
      valuesFrom:
      - secretRef:
          name: octant-values
