apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: package-repo-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: tanzu-std-161u1
  namespace: packages
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tkg/packages/standard/repo:v1.6.1_update.1