apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: package-repo-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: tanzu-std-22u2
  namespace: packages
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tkg/packages/standard/repo:v2.2.0_update.2