#@data/values
---
tld_domain: tmc.h2o-4-12022.h2o.vmware.com     #! enter the domain. a subdomain like "tmc." is recommended as in the example.
harbor:
  fqdn: harbor.tmc.h2o-4-12022.h2o.vmware.com  #! enter the Harbor FQDN. No "http"/"https" needed.
  user: admin                                  #! enter the Harbor username
  pass: VMware1!                               #! enter the Harbor password
std_repo: v2.2.0_update.2                      #! enter the tanzu package version. You do not need to change that with current release.
tmc_repo: 1.0.0-rc.4                           #! enter the tmc package version.
loadbalancer_ip: 10.220.67.102                 #! define and enter an empty loadbalancer ip address from the loadbalancer subnet.
auth:
  ldap:
    enabled: true                              #! true or false . if you want openldap to be configured automatically, enable this.
  oidc:
    enabled: false                             #! true or false . if you want to use OIDC identity provider, enable this.
    issuerURL: https://asd                     #! enter OIDC url
    clientID: asd                              #! enter OIDC clientID
    clientSecret: asd                          #! enter OIDC clientSecret
shared_cluster:
  namespace: platform                          #! the tmc cluster that is going to be provisioned, will be in this vSphere namespace
  k8s_version: v1.23.8---vmware.3-tkg.1        #! the tmc cluster that is going to be provisioned, will use this k8s version
  storage: tanzu                               #! the tmc cluster that is going to be provisioned, will use this storage
workload_cluster:
  name: dev                                    #! Only for vSphere 8. the name of workload cluster that is going to be provisioned
  namespace: dev                               #! Only for vSphere 8. the namespace of workload cluster that is going to be provisioned
  k8s_version: v1.23.8---vmware.3-tkg.1        #! Only for vSphere 8. the k8s version of workload cluster that is going to be provisioned
  storage: tanzu                               #! Only for vSphere 8. the storage of workload cluster that is going to be provisioned
wcp:
  ip: 10.220.65.100                            #! supervisor ip
  user: administrator@vsphere.local            #! username
  password: VMware1!                           #! password
vcenter:
  fqdn: vc01.h2o-4-12022.h2o.vmware.com        #! vCenter FQDN or IP. No "http"/"https" needed.
trustedCAs:                                    #! Certificate section
  #! Paste tmc-ca.crt / Example: CA Cert for *.tmc.corp.com / This will be be Root CA for TMC-SM's domain.
  tmc_ca: |-
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIJAKWUQptOQgoxMA0GCSqGSIb3DQEBCwUAMIGEMQswCQYD
    VQQGEwJUUjERMA8GA1UECAwISXN0YW5idWwxETAPBgNVBAcMCElzdGFuYnVsMRcw
    ...
    /2A0B00jNxmc6u7hZ6tVvZhaYMuVzFdTlcLMCuO9hC8DoqX/SP/o3MFkN/cswA0c
    A68ATA67uSZlkBcUVFMT8mNzIahK82WwHP0/cG+bAMypwidUOzJ+WvHaix4AtcIZ
    aNWuv2Wcc5ebQWexaw0frvY=
    -----END CERTIFICATE-----
  #! Paste tmc-ca-no-pass.key / Example: CA Key for *.tmc.corp.com / If you're using your own certs, add your un-encrypted Root CA Cert Key.
  tmc_key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKgIBAAKCAgEA7xcuX9hnmbUoFKsdvO2XnEP+M42dksAWOJso/x78xulDYQQs
    ...
    MlgzPM32OSjhyErlj1aOFPRIJXGg3cPRWCoHV51f2lzUXdLkJIWcwQhWXTealw==
    -----END RSA PRIVATE KEY-----
  #! Paste other ca.crt files / Example: CA Cert for *.tap.corp.com / If you don't have other CAs remove the values from line 54 to 61.
  other_ca: |-
    -----BEGIN CERTIFICATE-----
    MIIFrTCCA5WgAwIBAgIJAIjU55dYs8ORMA0GCSqGSIb3DQEBCwUAMIGEMQswCQYD
    VQQGEwJUUjERMA8GA1UECAwISXN0YW5idWwxETAPBgNVBAcMCElzdGFuYnVsMRcw
    ...
    wpzYazH1Y/xwH7lrZ7zL8WDtYSNCtNKlpIpOmT7bRGHHabB4CkfQmZgIlQhDXs6r
    bhsM31ea8EuDv9orDHfHPTo=
    -----END CERTIFICATE-----