#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
#@ if data.values.prometheus.deploy:
apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-extension-sa
  namespace: tanzu-system-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-extension-role
  namespace: tanzu-system-monitoring
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-extension-rolebinding
  namespace: tanzu-system-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-extension-role
subjects:
- kind: ServiceAccount
  name: prometheus-extension-sa
  namespace: tanzu-system-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-extension-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["clusterroles", "clusterrolebindings", "storageclasses"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-extension-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-extension-cluster-role
subjects:
- kind: ServiceAccount
  name: prometheus-extension-sa
  namespace: tanzu-system-monitoring
---
apiVersion: v1
data:
  values.yaml: #@ base64.encode(data.values.prometheus.overlay)
kind: Secret
metadata:
  name: prometheus-data-values
  namespace: tanzu-system-monitoring
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server-httpproxy
  namespace: tanzu-system-monitoring
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: prometheus-server
      port: 80
  virtualhost:
    fqdn: #@ "prometheus." + data.values.shared.ingress
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: prometheus
  namespace: tanzu-system-monitoring
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  syncPeriod: 5m
  serviceAccountName: prometheus-extension-sa
  fetch:
    - image:
        url: #@ data.values.tkgextensions.image
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - tkg-extensions/common
          - tkg-extensions/monitoring/prometheus
        inline:
          pathsFrom:
            - secretRef:
                name: prometheus-data-values
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]
#@ end