---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: elasticsearch
  namespace: tanzu-system-logging
spec:
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    services:
    - name: elasticsearch
      port: 9200
  virtualhost:
    fqdn: elastic.apps.h2o-4-12014.h2o.vmware.com
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus
  namespace: tanzu-system-monitoring
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: prometheus-server
      port: 80
  - conditions:
    - prefix: /alertmanager/
    pathRewritePolicy:
      replacePrefix:
      - prefix: /alertmanager/
        replacement: /
    services:
    - name: alertmanager
      port: 80
  virtualhost:
    fqdn: prometheus.apps.h2o-4-12014.h2o.vmware.com
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: tanzu-system-dashboards
spec:
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    services:
    - name: grafana
      port: 80
  virtualhost:
    fqdn: grafana.apps.h2o-4-12014.h2o.vmware.com
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kibana
  namespace: tanzu-system-logging
spec:
  routes:
  - conditions:
    - prefix: /
    enableWebsockets: true
    services:
    - name: kibana
      port: 5601
  virtualhost:
    fqdn: kibana.apps.h2o-4-12014.h2o.vmware.com