apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: openldap
spec: {}
status: {}
---
# Source: openldap/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "cGFzc3dvcmQ="
  LDAP_CONFIG_PASSWORD: "cGFzc3dvcmQ="
---
# Source: openldap/templates/configmap-customldif.yaml
#
# A ConfigMap spec for openldap slapd that map directly to files under
# /container/service/slapd/assets/config/bootstrap/ldif/custom
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-customldif
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
data:
  0-initial-ous.ldif: |-
    dn: ou=People,dc=ssotest,dc=mgt,dc=mytanzu,dc=org
    objectClass: organizationalUnit
    ou: People

    dn: ou=Group,dc=ssotest,dc=mgt,dc=mytanzu,dc=org
    objectClass: organizationalUnit
    ou: Group
---
# Source: openldap/templates/configmap-env.yaml
#
# A ConfigMap spec for openldap slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://github.com/osixia/docker-openldap#beginner-guide
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-env
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
data:
  LDAP_BACKEND: hdb
  LDAP_DOMAIN: ssotest.mgt.mytanzu.org
  LDAP_ORGANISATION: VMware Tanzu POC
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_MASSWORD: password
  LDAP_READONLY_USER_USERNAME: readonly
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
---
# Source: openldap/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: openldap/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
spec:
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: ldap-port
    - name: ssl-ldap-port
      protocol: TCP
      port: 636
      targetPort: ssl-ldap-port
  selector:
    app: openldap
    release: openldap
  type: ClusterIP
---
# Source: openldap/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  openldap
  namespace: openldap
  labels:
    app: openldap
    chart: openldap-1.2.7
    release: openldap
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
      release: openldap
  template:
    metadata:
      annotations:
        checksum/configmap-env: b502f31965efa9ea311c824f4b24d0aeec8de07153c6ae790375455eafeada80
        checksum/configmap-customldif: 456fe383c8b6c9aeccc479f7bd02eb5685596f3ccfada03de8c8384d8036216f
      labels:
        app: openldap
        release: openldap
    spec:
      initContainers:
      - name: openldap-init-ldif
        image: harbor.mgt.mytanzu.org/tools/busybox:latest
        command: ['sh', '-c', 'cp /customldif/* /ldifworkingdir']
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: customldif
          mountPath: /customldif
        - name: ldifworkingdir
          mountPath: /ldifworkingdir
        resources:
          {}
      containers:
        - name: openldap
          image: "harbor.mgt.mytanzu.org/tools/openldap:1.2.4"
          imagePullPolicy: IfNotPresent
          args:
            - -l
            - info
            - --copy-service
          ports:
            - name: ldap-port
              containerPort: 389
            - name: ssl-ldap-port
              containerPort: 636
          envFrom:
            - configMapRef:
                name: openldap-env
            - secretRef:
                name: openldap
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: data
            - name: data
              mountPath: /etc/ldap/slapd.d
              subPath: config-data
            - name: ldifworkingdir
              mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
          livenessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {}
      volumes:
        - name: customldif
          configMap:
            name: openldap-customldif
        - name: ldifworkingdir
          emptyDir: {}
        - name: certs
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: openldap
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
  namespace: openldap
spec:
  commonName: ldaps.mgt.mytanzu.org
  dnsNames:
  - ldaps.mgt.mytanzu.org
  ipNames:
  - 34.118.30.44
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: openldap-tls
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ldap
  namespace: openldap
spec:
  routes:
  - services:
    - name: openldap
      port: 389
  virtualhost:
    fqdn: ldap.mgt.mytanzu.org
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ldaps
  namespace: openldap
spec:
  virtualhost:
    fqdn: ldaps.mgt.mytanzu.org
    tls:
      secretName: openldap-tls
  tcpproxy:
    services:
    - name: openldap
      port: 636
      protocol: tls
