apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: package-repo-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: tanzu-repo-v2.1.0
  namespace: vmware-system-tkg
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tkg/packages/standard/repo:v2.1.0
