#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  pg_password: cGFzc3dvcmQxMjM= #!password123
  pg_username: YWRtaW51c2Vy #!adminuser
  pg_host: cG9zdGdyZXMtc3Zj #!postgres-svc
  pg_port: NTQzMg== #!5432
  pg_dbname: YXBw #!app
  type: YXBwLWNvbmZpZwo= #!app-config
kind: Secret
metadata:
  name: postgres-creds
  namespace: #@ "{}".format(data.values.namespace)
---
apiVersion: v1
data:
  rbmq_password: Z3Vlc3Q= #!guest
  rbmq_username: Z3Vlc3Q= #!guest
  rbmq_host: cmFiYml0bXE= #!rabbitmq
  rbmq_port: NTY3Mg== #!5672
  rbmq_queue: dGVzdC1xdWV1ZQ== #!test-queue
  type: YXBwLWNvbmZpZwo= #!app-config
kind: Secret
metadata:
  name: rbmq-creds
  namespace: #@ "{}".format(data.values.namespace)
---
apiVersion: v1
data:
  mongo_password: cGFzc3dvcmQxMjM= #!password123
  mongo_username: YWRtaW51c2Vy #!adminuser
  mongo_host: bW9uZ28tc3Zj #!mongo-svc
  mongo_port: MjcwMTc= #!27017
  type: YXBwLWNvbmZpZwo= #!app-config
kind: Secret
metadata:
  name: mongo-creds
  namespace: #@ "{}".format(data.values.namespace)
---
apiVersion: v1
data:
  redis_password: cGFzc3dvcmQxMjM= #!password123
  redis_username: ZGVmYXVsdA== #!default
  redis_host: cmVkaXMtc3Zj #!redis-svc
  redis_port: NjM3OQ== #!6379
  type: YXBwLWNvbmZpZw== #!app-config
kind: Secret
metadata:
  name: redis-creds
  namespace: #@ "{}".format(data.values.namespace)
---
apiVersion: v1
data:
  mysql_password: cGFzc3dvcmQxMjM= #!password123
  mysql_username: cm9vdA== #!root
  mysql_host: bXlzcWwtc3Zj #!mysql-svc
  mysql_port: MzMwNg== #!3306
  type: YXBwLWNvbmZpZwo= #!app-config
kind: Secret
metadata:
  name: mysql-creds
  namespace: #@ "{}".format(data.values.namespace)
---
apiVersion: v1
data:
  elastic_host: ZWxhc3RpYy1zdmM= #!elastic-svc
  elastic_port: OTIwMA== #!9200
  type: YXBwLWNvbmZpZwo= #!app-config
kind: Secret
metadata:
  name: elastic-creds
  namespace: #@ "{}".format(data.values.namespace)
---
apiVersion: v1
data:
  username: #@ base64.encode(data.values.app.user)
  password: #@ base64.encode(data.values.app.passw)
kind: Secret
metadata:
  name: gorkem-secret
  namespace: #@ "{}".format(data.values.namespace)
type: Opaque