#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
data:
  corp-ca-1: #@ base64.encode(base64.encode("{}\n{}".format(data.values.trustedCAs.tmc_ca,data.values.trustedCAs.other_ca)))
kind: Secret
metadata:
  name: #@ "{}-user-trusted-ca-secret".format(data.values.workload_cluster.name)
  namespace: #@ "{}".format(data.values.workload_cluster.namespace)
type: Opaque
---
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: KappControllerConfig
metadata:
  name:  #@ "{}".format(data.values.workload_cluster.name)
  namespace: #@ "{}".format(data.values.workload_cluster.namespace)
spec:
  kappController:
    createNamespace: false
    config:
      caCerts: #@ "{}\n{}".format(data.values.trustedCAs.tmc_ca,data.values.trustedCAs.other_ca)
      dangerousSkipTLSVerify: ""
      httpProxy: ""
      httpsProxy: ""
      noProxy: ""
    deployment:
      apiPort: 10100
      concurrency: 4
      hostNetwork: true
      metricsBindAddress: "0"
      priorityClassName: system-cluster-critical
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
    globalNamespace: tkg-system
  namespace: tkg-system
---
apiVersion: run.tanzu.vmware.com/v1alpha3
kind: ClusterBootstrap
metadata:
  name: #@ "{}".format(data.values.workload_cluster.name)
  namespace: #@ "{}".format(data.values.workload_cluster.namespace)
  annotations:
    tkg.tanzu.vmware.com/add-missing-fields-from-tkr: #@ "{}".format(data.values.workload_cluster.k8s_version)
spec:
  kapp:
    refName: kapp-controller.tanzu.vmware.com.0.41.5+vmware.1-tkg.1
    valuesFrom:
      providerRef:
        apiGroup: run.tanzu.vmware.com
        kind: KappControllerConfig
        name: #@ "{}".format(data.values.workload_cluster.name)