---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: prometheus-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: prometheus-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: prometheus-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: prometheus-packages-sa
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: alertmanager-overlay
    kapp.k14s.io/update-strategy: "fallback-on-replace"
    kapp.k14s.io/create-strategy: "fallback-on-replace"
  name: prometheus
  namespace: packages
spec:
  packageRef:
    refName: prometheus.tanzu.vmware.com
    versionSelection:
      constraints: 2.36.2+vmware.1-tkg.1
  serviceAccountName: prometheus-packages-sa
  values:
  - secretRef:
      name: prometheus-packages-values
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus
  namespace: tanzu-system-monitoring
spec:
  routes:
  - conditions:
    - prefix: /
    pathRewritePolicy:
      replacePrefix:
      - prefix: /
        replacement: /
    services:
    - name: prometheus-server
      port: 80
  - conditions:
    - prefix: /alertmanager/
    pathRewritePolicy:
      replacePrefix:
      - prefix: /alertmanager/
        replacement: /
    services:
    - name: alertmanager
      port: 80
  virtualhost:
    fqdn: prometheus.apps.h2o-4-12014.h2o.vmware.com